# Generated by Django 6.1.1 on 2026-09-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'permissions': [('manage_genres', 'Gestionar géneros (CRUD completo)')], 'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_year', 'title'], 'permissions': [('view_movie_stats', 'Ver estadísticas de películas'), ('export_movie_data', 'Exportar datos de películas'), ('publish_movie', 'Publicar película')], 'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('view_person_filmography', 'Ver filmografía de persona')], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at'], 'permissions': [('moderate_rating', 'Moderar valoraciones (editar/borrar cualquier)')], 'verbose_name': 'Valoración', 'verbose_name_plural': 'Valoraciones'},
        ),
    ]
